name: Trigger Release

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-review:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger release
      uses: edgedb/action-release/trigger@master
      with:
        github_token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
        release_validation_check: "validate-release-request"
